# Generated by Django 5.1.2 on 2024-11-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='function_order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='daily_order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.orders'),
        ),
    ]
