# Generated by Django 5.1.2 on 2024-11-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_debtcustomer_functiondebtcustomer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunctionDebtCustomer',
        ),
    ]
