# Generated by Django 5.1.2 on 2024-11-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_functiondebtcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='function_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='daily_order_id',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='is_function',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='FunctionOrderItems',
        ),
        migrations.DeleteModel(
            name='FunctionOrders',
        ),
    ]
