# Generated by Django 5.1.2 on 2024-11-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
